version: "3"
services:
  3dcitydb:
    container_name: 00_3dcitydb_00_database
    image: 3dcitydb/3dcitydb-pg:14-3.2-4.1.0
    ports:
      - "5432:5432"
    environment:
      SRID: 25832
      POSTGRES_DB: city
      POSTGRES_USER: city
      POSTGRES_PASSWORD: city
    restart: always

  3dcitydbweb:
    tty: true
    stdin_open: true
    container_name: 00_3dcitydb_01_web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
        TZ: "Asia/Seoul"
    volumes:
      - ./data:/usr/src/app/3dcity/data

  #3dcitydb-web-map-test:
  #  container_name: <web name>
  #  build:
  #    context: .
  #    dockerfile: ./Dockerfile
  #  volumes:
  #    - <data>:/var/www/data/
  #  ports:
  #    - "<web outport>:8000"
  #  restart: always
